// <auto-generated />
namespace Facturacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifi));
        
        string IMigrationMetadata.Id
        {
            get { return "201708092141191_modifi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
